config/routes.rb
Rails.application.routes.draw do
  get '/welcome' => 'users#welcome', as: :welcome
  get '/home' => 'categories#index', as: :home
  get '/categories/new' => 'categories#new', as: :new_category
  get '/categories/:category_id/payment' => 'payments#index', as: :payments
  get '/categories/:category_id/payment/new' => 'payments#new', as: :new_payment

  post '/categories' => 'categories#create'
  post '/categories/:category_id/payment' => 'payments#create'

  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users/password' => 'devise/passwords#update'
  end

  get "up" => "rails/health#show", as: :rails_health_check

  authenticated :user do
    root "categories#index", as: :authenticated_root
  end

  unauthenticated do
    root "users#welcome", as: :unauthenticated_root
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :category_payments

  validates :name, presence: true
  validates :icon, presence: true
  validates :user_id, presence: true
end

app/models/category_payment.rb
class CategoryPayment < ApplicationRecord
  belongs_to :category
  belongs_to :payment

  validates :category_id, presence: true
  validates :payment_id, presence: true
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user, foreign_key: 'author_id'
  has_many :category_payments

  validates :name, presence: true
  validates :amount, presence: true
  validates :author_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories
  has_many :payments, foreign_key: 'author_id'

  validates :name, presence: true
  validates :email, presence: true
  validates :encrypted_password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_registration_parameters, if: :devise_controller?

  protected

  def configure_registration_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :bio) }
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  def index
    @categories = Category.where(user_id: current_user.id)
    @payments = Payment.joins(:category_payments)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to home_path, notice: 'Category was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon, :user_id)
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :authenticate_user!

  def index
    @category = Category.find(params[:category_id])
    @payments = Payment.joins(:category_payments).where(category_payments: { category_id: @category.id })
      .order(created_at: :desc)
  end

  def new
    @payment = Payment.new
    @categories = Category.where(user_id: current_user.id)
  end

  def create
    @categories = Category.where(user_id: current_user.id)
    success = false
    unless params[:category_ids].nil?
      category = Category.find(params[:category_id])
      @payment = Payment.new(payment_params)
      category_ids = params[:category_ids]

      if @payment.save
        category_ids.each do |category_id|
          @category_payment = CategoryPayment.new(category_id:, payment_id: @payment.id)
          success = true if @category_payment.save
        end
      end
    end

    if success
      flash[:notice] = 'Category payment was successfully created.'
      redirect_to "/categories/#{category.id}/payment"
    else
      @payment = Payment.new
      render :new, status: :unprocessable_entity, locals: { payment: @payment }
    end
  end

  private

  def payment_params
    params.require(:payment).permit(:name, :amount, :author_id)
  end

  def category_payment_params
    params.require(:category_payment).permit(:payment_id, category_ids: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include Devise::Controllers::Helpers

  def welcome; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>

  <p>
    <strong>Icon:</strong>
    <%= category.icon %>
  </p>

  <p>
    <strong>User:</strong>
    <%= category.user_id %>
  </p>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category, id: 'new_category') do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :user_id, value: current_user.id%>

  <div>
    <%= form.text_field :name, placeholder: 'Category Name' %>
  </div>

  <p id='icon-instruction'>Choose an icon</p>

  <div class = 'grid-icons'>
    
    <%= form.label :entertainment_icon do %>
      <%= form.radio_button :icon, "fa-solid fa-masks-theater fa-xl", class: "radio-input" %>
      <i class="fa-solid fa-masks-theater fa-xl icon"></i>
    <% end %>

    <%= form.label :health_icon do %>
      <%= form.radio_button :icon, "fa-solid fa-heart-pulse fa-xl", class: "radio-input" %>
      <i class="fa-solid fa-heart-pulse fa-xl icon"></i>
    <% end %>

    <%= form.label :fitness_icon do %>
      <%= form.radio_button :icon, "fa-solid fa-dumbbell fa-xl", class: "radio-input" %>
      <i class="fa-solid fa-dumbbell fa-xl icon"></i>
    <% end %>

    <%= form.label :travel_icon do %>
      <%= form.radio_button :icon, "fa-solid fa-person-walking-luggage fa-2xl", class: "radio-input" %>
      <i class="fa-solid fa-person-walking-luggage fa-xl icon"></i>
    <% end %>

    <%= form.label :shopping_icon do %>
      <%= form.radio_button :icon, "fa-solid fa-cart-shopping fa-xl", class: "radio-input" %>
      <i class="fa-solid fa-cart-shopping fa-xl icon"></i>
    <% end %>

    <%= form.label :bills_icon do %>
      <%= form.radio_button :icon, "fa-solid fa-file-invoice-dollar fa-xl", class: "radio-input" %>
      <i class="fa-solid fa-file-invoice-dollar fa-xl icon"></i>
    <% end %>

    <%= form.label :dining_icon do %>
      <%= form.radio_button :icon, "fa-solid fa-utensils fa-xl", class: "radio-input" %>
      <i class="fa-solid fa-utensils fa-xl icon"></i>
    <% end %>

    <%= form.label :giving_icon do %>
      <%= form.radio_button :icon, "fa-solid fa-hand-holding-heart fa-xl", class: "radio-input" %>
      <i class="fa-solid fa-hand-holding-heart fa-xl icon"></i>
    <% end %>
  </div>
<% end %>

app/views/categories/index.html.erb
<section id='home'>
  <div class='top-section'>
    <div>&nbsp;</div>
    <h3>Home</h3>
    <%= link_to "Sign Out", destroy_user_session_path, method: :get, class: 'form-submit' %>
  </div>

  <div id="categories" class='flex-col'>
    <% @categories.each do |category| %>
      <% @expenditures = @payments.where(category_payments: { category_id: category.id }) %>
      <a class="category-link" href=<%=payments_path(category.id)%>>
        <div class='category flex-row'>
          <i class="<%= category.icon %> icon"></i>
          <div class='category_details'>
            <p class='category_name' ><%=category.name%></p>
            <p class='category_amount'>$<%= format("%.2f", @expenditures.sum(:amount))%></p>
          </div>
        </div>
      </a>
    <% end %>
  </div>
  <div class='green-button-container'>
    <%= link_to "New Category", new_category_path, class: 'green-button' %>
  </div>

</section>

app/views/categories/new.html.erb
<section class='form-page'>
    <div id='new-category-top-section'>
    <a class='back-arrow' href= <%= home_path%>><i class="fas fa-arrow-left"></i></a>
    <h3>New Category</h3>
  </div>

  

  <%= render "form", category: @category %>

  <div class='green-button-container'>
    <input type='submit' form='new_category' name='commit' value='Create Category' data-disable-with='Create Category' class='green-button'>
  </div>

</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoneyMate</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main>
      <p class="notice" style="color: green"><%= notice %></p>
      <p class="alert" style="color: red"><%= alert %></p>
      <%= yield %>
    </main>
  </body>
</html>

app/views/payments/_form.html.erb
<%= form_with(model: payment, html: {id: 'payment-form'})  do |form| %>
  <% if payment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
        <% payment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :author_id, value: current_user.id%>

  <div>
    <%= form.text_field :name, placeholder: 'Transaction Name' %>
  </div>

  <div>
    <%= form.number_field :amount, step: 0.01, placeholder: 'Amount' %>
  </div>

  <p id='icon-instruction'>Choose at least one category</p>

  <div class = 'transaction-categories flex-col'>
    <%@categories.each do |category|%>
      <div class='transaction-category-details'>
        <input type="checkbox" name="category_ids[]" value="<%= category.id %>">
          <i class="<%= category.icon %> icon"></i>
          <p><%= category.name %></p>
      </div>
    <%end%>
  </div>
<% end %>

app/views/payments/index.html.erb
<section id='transactions'>
  <div class='top-section'>
    <a class='back-arrow' href= <%= home_path%>><i class="fas fa-arrow-left"></i></a>
    <h3>Transactions</h3>
    <div>&nbsp;</div>
  </div>

  <div id='total-transactions' class='flex-row'>
    <h4><%= @category.name%></h4>
    <p>Total: $<%= format("%.2f", @payments.sum(:amount))%></p>
  </div>

  <div id="payments">
    <% @payments.each do |payment| %>
    <div class='payment flex-col'>
        <div class='details flex-row'>
          <p><%= payment.name %></p>
          <p>$<%= format("%.2f", payment.amount) %></p>
        </div>
        <p class='date'> <%= payment.created_at.strftime('%d-%b-%Y') %> </p>
      </div>
    <% end %>
  </div>

  <div class='green-button-container'>
    <%= link_to "New Transaction", new_payment_path(@category.id), class: 'green-button' %>
  </div>
</section>

app/views/payments/new.html.erb
<section class='form-page'>
    <div id='new-payment-top-section'>
    <a class='back-arrow' href= <%= payments_path%>><i class="fas fa-arrow-left"></i></a>
    <h3>New Transaction</h3>
  </div>

  

  <%= render "form", payment: @payment %>

  <div class='green-button-container'>
    <input type='submit' form='payment-form' name='commit' value='Record Transaction' data-disable-with='Record Transaction' class='green-button'>
  </div>

</section>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/welcome.html.erb
<section id='welcome' class='flex-col'>
  <h1 id='app-name'>MoneyMate</h1>
  <div id='welcome-buttons'>
    <%= button_to "LOG IN", new_user_session_path, method: :get, id: 'login-button' %>
    <%= button_to "SIGN UP", new_user_registration_path, method: :get, id: 'signup-button' %>
  <div>
</section>